"""Authored sample fixture for PRism facts engine tests.

This file is the fictional Python source that the sample_pr.patch
diff is based on.  It represents the NEW (b-side) state of the file
after the patch is applied.

Do NOT edit this file without also updating sample_pr.patch to match.
"""
from __future__ import annotations

import hashlib
import logging
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Utility: hex digest helper
# ---------------------------------------------------------------------------


def sha256_hex(data: bytes) -> str:
    """Return the lowercase hex SHA-256 of *data*."""
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# DiffStats — new in this PR
# ---------------------------------------------------------------------------


class DiffStats:
    """Lightweight diff statistics container.

    Added in this PR to expose per-file line counts without
    loading the full diff text into memory.
    """

    def __init__(self, added: int, removed: int) -> None:
        if added < 0 or removed < 0:
            raise ValueError("Line counts must be non-negative")
        self.added = added
        self.removed = removed

    @property
    def net(self) -> int:
        """Net line change (positive = net additions)."""
        return self.added - self.removed

    def __repr__(self) -> str:
        return f"DiffStats(added={self.added}, removed={self.removed})"
